### ISSUE TITLE
Open source EpubPress backend

### ISSUE THREAD

**Issue by haroldtreen** [haroldtreen/epub-press-clients#17]
I'm now working for Squarespace and have less time to maintain the backend code. I'd like to open source it so others can add features without waiting on me.

## Todo

- [ ] Audit commit history for sensitive data.
- [ ] Write better documentation.
- [ ] Keep the clients and backend within an EpubPress organization?
- [ ] Add appropriate license info.

**Comment by shaenchen** [comment]
Eager to see it, following...

**Comment by haroldtreen** [comment]
Sorry for the silence @shaenchen !

I'm blocked on cleaning the git history. I was also hoping to work on proper docs, but that can wait. 

Currently I've been focused on custom covers, as a bunch of people have requested that and I'm very close to done!

But I hope to get back on this shortly. Thanks for your patience!

**Comment by msdos** [comment]
Any news on this? Will it be possible to convert an url to epub using a CLI app?

**Comment by haroldtreen** [comment]
No progress @msdos . Had relatively little time and been focused on features like custom cover images.

The backend is an `express` app though - so no plans for a CLI.

**Comment by asmyers** [comment]
Would love to see this happen.  I've been running into the size and number of images limits and it would be great to self host to avoid them.

**Comment by haroldtreen** [comment]
EpubPress is now fully open source!
You can checkout the backend code here: https://github.com/haroldtreen/epub-press

I'll be working move the relevant issues over to that repo.

Hope it's all you dreamed of and more ❤️ .
